apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true","release.openshift.io/create-only":"true"},"creationTimestamp":"2023-09-28T14:08:46Z","generation":3,"name":"cluster","ownerReferences":[{"apiVersion":"config.openshift.io/v1","kind":"ClusterVersion","name":"version","uid":"72d0e456-95f1-4410-926d-04980c8ba544"}],"resourceVersion":"332963","uid":"c8ba3aad-8360-4c1b-9049-00410bc5d2eb"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpasswd-secret-02"}},"mappingMethod":"claim","name":"devops-htpasswd-provider","type":"HTPasswd"},{"ldap":{"attributes":{"email":["mail"],"id":["dn"],"name":["cn"],"preferredUsername":["uid"]},"bindDN":"uid=admin,cn=users,cn=accounts,dc=ocp4,dc=example,dc=com","bindPassword":{"name":"ldap-secret"},"ca":{"name":"ca-config-map"},"insecure":false,"url":"ldap://idm.ocp4.example.com/cn=users,cn=accounts,dc=ocp4,dc=example,dc=com?uid"},"mappingMethod":"claim","name":"Red Hat Identity Management","type":"LDAP"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2023-09-28T14:08:46Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 72d0e456-95f1-4410-926d-04980c8ba544
  resourceVersion: "597873"
  uid: c8ba3aad-8360-4c1b-9049-00410bc5d2eb
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: sre-secret
    mappingMethod: claim
    name: sre-htpasswd-provider
    type: HTPasswd

  - htpasswd:
      fileData:
        name: devops-secret
    mappingMethod: claim
    name: devops-htpasswd-provider
    type: HTPasswd

  - htpasswd:
      fileData:
        name: app-secret
    mappingMethod: claim
    name: app-htpasswd-provider
    type: HTPasswd

  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=admin,cn=users,cn=accounts,dc=ocp4,dc=example,dc=com
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldap://idm.ocp4.example.com/cn=users,cn=accounts,dc=ocp4,dc=example,dc=com?uid
    mappingMethod: claim
    name: Red Hat Identity Management
    type: LDAP
