apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
 limits:
 - type: "Pod"
   max:
     cpu: "250m"
     memory: "250Mi"
   min:
     cpu: "100m"
     memory: "100Mi"
 - type: "Container"
   max:
     cpu: "250m"
     memory: "250Mi"
   min:
     cpu: "100m"
     memory: "100Mi"
   defaultRequest:
     cpu: "150m"
     memory: "150Mi"
